### ISSUE TITLE
希望能提供方便 Web 使用的 WOFF 与 WOFF2 格式

### ISSUE THREAD

**Issue by shirok1** [ACh-K/Cubic-11#1]
我很喜欢您制作的这款字体，希望能将它用在我的网页设计上，我目前使用[谷歌的转换工具](https://github.com/google/woff2)来把 TTF 文件转换为 WOFF2，但是对效果不是很满意。

![图片](https://user-images.githubusercontent.com/12044683/155008539-00cb0f61-506e-49ad-bd98-fa73a869282f.png)

这是在字体预览处的效果：

![图片](https://user-images.githubusercontent.com/12044683/155008650-3e9e00b6-a1d9-4c24-8c31-6b179dd452a0.png)

不知道您使用的字体设计软件是否支持直接输出 WOFF 和 WOFF2 格式？如果支持的话请发布以这两种 Web 使用的字体格式的版本。（最好能两个版本都发布因为各有优势）

P.S. 也请考虑直接发布字体设计的源文件

**Comment by ACh-K** [comment]
俐方體剛剛釋出了更新，新增了 woff 和 woff2 的字型格式

**Comment by shirok1** [comment]
非常感谢
