### ISSUE TITLE
mac上的一些文字異常

### ISSUE THREAD

**Issue by EndRollModel** [ACh-K/Cubic-11#2]
感謝提供字型 非常喜歡像素風格的內容 

使用此字型於mac上測試網頁內容時 發現有部分字型異常
稍微測試後發現好像是只有mac才有此問題
試問此問題是mac的問題或是字型問題？
(因為沒看到有人有類似問題 懷疑是自己電腦出問題而已
若其他人沒有問題 請close此issue 不好意思)

測試資訊如下 
測試環境 ： macOS Catalina (10.15.7) 上的chrome(97.0.4692.99), safari(15.1)
測試文字 ： 常用國字標準字體 4808 字, 英文字母, 數字, 注音, 標點符號
異常文字 ： 8, 0, 小寫o

異常文字圖片 ：
![image](https://user-images.githubusercontent.com/51425629/155644521-41eef267-7514-4684-9830-b2a5b5e3420e.png)

**Comment by ACh-K** [comment]
抱歉久等了！🙏目前新版本已經發布，不過因為手邊沒有 macOS 可以確認，所以想在此詢問，該問題是否已解決？

**Comment by EndRollModel** [comment]
目前套用Version 1.013的字體(ttf, woff, woff2)後(chrom, safari)都已正常顯示
非常感謝
